import { TestScheduler } from "jest";
import ExchangeRate from "../src/exchange-rate.js";

describe("exchange-rate", () => {
  let exchange;

  beforeEach(() => {
    exchange = new ExchangeRate();
  });

  test("should return a string containing the name of the currency associated to each currency code the Api provided", () => {
    expect(exchange.aed).toEqual("UAE Dirham");
    expect(exchange.afn).toEqual("Afghan Afghani");
    expect(exchange.all).toEqual("Albanian Lek");
    expect(exchange.amd).toEqual("Armenian Dram");
    expect(exchange.ang).toEqual("Netherlands Antillian Guilder");
    expect(exchange.aoa).toEqual("Angolan Kwanza");
    expect(exchange.ars).toEqual("Argentine Peso");
    expect(exchange.aud).toEqual("Australian Dollar");
    expect(exchange.awg).toEqual("Aruban Florin");
    expect(exchange.azn).toEqual("Azerbaijani Manat");
    expect(exchange.bam).toEqual("Bosnia and Herzegovina Mark");
    expect(exchange.bbd).toEqual("Barbados Dollar");
    expect(exchange.bdt).toEqual("Bangladeshi Taka");
    expect(exchange.bgn).toEqual("Bulgarian Lev");
    expect(exchange.bhd).toEqual("Bahraini Dinar");
    expect(exchange.bif).toEqual("Burundian Franc");
    expect(exchange.bmd).toEqual("Bermudian Dollar");
    expect(exchange.bnd).toEqual("Brunei Dollar");
    expect(exchange.bob).toEqual("Bolivian Boliviano");
    expect(exchange.brl).toEqual("Brazilian Real");
    expect(exchange.bsd).toEqual("Bahamian Dollar");
    expect(exchange.btn).toEqual("Bhutanese Ngultrum");
    expect(exchange.bwp).toEqual("Botswana Pula");
    expect(exchange.byn).toEqual("Belarusian Ruble");
    expect(exchange.bzd).toEqual("Belize Dollar");
    expect(exchange.cad).toEqual("Canadian Dollar");
    expect(exchange.cdf).toEqual("Congolese Franc");
    expect(exchange.chf).toEqual("Swiss Franc");
    expect(exchange.clp).toEqual("Chilean Peso");
    expect(exchange.cny).toEqual("Chinese Renminbi");
    expect(exchange.cop).toEqual("Colombian Peso");
    expect(exchange.crc).toEqual("Costa Rican Colon");
    expect(exchange.cuc).toEqual("Cuban Convertible Peso");
    expect(exchange.cup).toEqual("Cuban Peso");
    expect(exchange.cve).toEqual("Cape Verdean Escudo");
    expect(exchange.czk).toEqual("Czech Koruna");
    expect(exchange.djf).toEqual("Djiboutian Franc");
    expect(exchange.dkk).toEqual("Danish Krone");
    expect(exchange.dop).toEqual("Dominican Peso");
    expect(exchange.dzd).toEqual("Algerian Dinar");
    expect(exchange.egp).toEqual("Egyptian Pound");
    expect(exchange.ern).toEqual("Eritrean Nakfa");
    expect(exchange.etb).toEqual("Ethiopian Birr");
    expect(exchange.eur).toEqual("Euro");
    expect(exchange.fjd).toEqual("Fiji Dollar");
    expect(exchange.fkp).toEqual("Falkland Islands Pound");
    expect(exchange.fok).toEqual("Faroese Króna");
    expect(exchange.gbp).toEqual("Pound Sterling");
    expect(exchange.gel).toEqual("Georgian Lari");
    expect(exchange.ggp).toEqual("Guernsey Pound");
    expect(exchange.ghs).toEqual("Ghanaian Cedi");
    expect(exchange.gip).toEqual("Gibraltar Pound");
    expect(exchange.gmd).toEqual("Gambian Dalasi");
    expect(exchange.gnf).toEqual("Guinean Franc");
    expect(exchange.gtq).toEqual("Guatemalan Quetzal");
    expect(exchange.gyd).toEqual("Guyanese Dollar");
    expect(exchange.hkd).toEqual("Hong Kong Dollar");
    expect(exchange.hnl).toEqual("Honduran Lempira");
    expect(exchange.hrk).toEqual("Croatian Kuna");
    expect(exchange.htg).toEqual("Haitian Gourde");
    expect(exchange.huf).toEqual("Hungarian Forint");
    expect(exchange.idr).toEqual("Indonesian Rupiah");
    expect(exchange.ils).toEqual("Israeli New Shekel");
    expect(exchange.imp).toEqual("Manx Pound");
    expect(exchange.inr).toEqual("Indian Rupee");
    expect(exchange.iqd).toEqual("Iraqi Dinar");
    expect(exchange.irr).toEqual("Iranian Rial");
    expect(exchange.isk).toEqual("Icelandic Króna");
    expect(exchange.jmd).toEqual("Jamaican Dollar");
    expect(exchange.jod).toEqual("Jordanian Dinar");
    expect(exchange.jpy).toEqual("Japanese Yen");
    expect(exchange.kes).toEqual("Kenyan Shilling");
    expect(exchange.kgs).toEqual("Kyrgyzstani Som");
    expect(exchange.khr).toEqual("Cambodian Riel");
    expect(exchange.kid).toEqual("Kiribati Dollar");
    expect(exchange.kmf).toEqual("Comorian Franc");
    expect(exchange.krw).toEqual("South Korean Won");
    expect(exchange.kwd).toEqual("Kuwaiti Dinar");
    expect(exchange.kyd).toEqual("Cayman Islands Dollar");
    expect(exchange.kzt).toEqual("Kazakhstani Tenge");
    expect(exchange.lak).toEqual("Lao Kip");
    expect(exchange.lbp).toEqual("Lebanese Pound");
    expect(exchange.lkr).toEqual("Sri Lanka Rupee");
    expect(exchange.lrd).toEqual("Liberian Dollar");
    expect(exchange.lsl).toEqual("Lesotho Loti");
    expect(exchange.lyd).toEqual("Libyan Dinar");
    expect(exchange.mad).toEqual("Moroccan Dirham");
    expect(exchange.mdl).toEqual("Moldovan Leu");
    expect(exchange.mga).toEqual("Malagasy Ariary");
    expect(exchange.mkd).toEqual("Macedonian Denar");
    expect(exchange.mmk).toEqual("Burmese Kyat");
    expect(exchange.mnt).toEqual("Mongolian Tögrög");
    expect(exchange.mop).toEqual("Macanese Pataca");
    expect(exchange.mru).toEqual("Mauritanian Ouguiya");
    expect(exchange.mur).toEqual("Mauritian Rupee");
    expect(exchange.mvr).toEqual("Maldivian Rufiyaa");
    expect(exchange.mwk).toEqual("Malawian Kwacha");
    expect(exchange.mxn).toEqual("Mexican Peso");
    expect(exchange.myr).toEqual("Malaysian Ringgit");
    expect(exchange.mzn).toEqual("Mozambican Metical");
    expect(exchange.nad).toEqual("Namibian Dollar");
    expect(exchange.ngn).toEqual("Nigerian Naira");
    expect(exchange.nio).toEqual("Nicaraguan Córdoba");
    expect(exchange.nok).toEqual("Norwegian Krone");
    expect(exchange.npr).toEqual("Nepalese Rupee");
    expect(exchange.nzd).toEqual("New Zealand Dollar");
    expect(exchange.omr).toEqual("Omani Rial");
    expect(exchange.pab).toEqual("Panamanian Balboa");
    expect(exchange.pen).toEqual("Peruvian Sol");
    expect(exchange.pgk).toEqual("Papua New Guinean Kina");
    expect(exchange.php).toEqual("Philippine Peso");
    expect(exchange.pkr).toEqual("Pakistani Rupee");
    expect(exchange.pln).toEqual("Polish Złoty");
    expect(exchange.pyg).toEqual("Paraguayan Guaraní");
    expect(exchange.qar).toEqual("Qatari Riyal");
    expect(exchange.ron).toEqual("Romanian Leu");
    expect(exchange.rsd).toEqual("Serbian Dinar");
    expect(exchange.rub).toEqual("Russian Ruble");
    expect(exchange.rwf).toEqual("Rwandan Franc");
    expect(exchange.sar).toEqual("Saudi Riyal");
    expect(exchange.sbd).toEqual("Solomon Islands Dollar");
    expect(exchange.scr).toEqual("Seychellois Rupee");
    expect(exchange.sdg).toEqual("Sudanese Pound");
    expect(exchange.sek).toEqual("Swedish Krona");
    expect(exchange.sgd).toEqual("Singapore Dollar");
    expect(exchange.shp).toEqual("Saint Helena Pound");
    expect(exchange.sll).toEqual("Sierra Leonean Leone");
    expect(exchange.sos).toEqual("Somali Shilling");
    expect(exchange.srd).toEqual("Surinamese Dollar");
    expect(exchange.ssp).toEqual("South Sudanese Pound");
    expect(exchange.stn).toEqual("São Tomé and Príncipe Dobra");
    expect(exchange.syp).toEqual("Syrian Pound");
    expect(exchange.szl).toEqual("Eswatini Lilangeni");
    expect(exchange.thb).toEqual("Thai Baht");
    expect(exchange.tjs).toEqual("Tajikistani Somoni");
    expect(exchange.tmt).toEqual("Turkmenistan Manat");
    expect(exchange.tnd).toEqual("Tunisian Dinar");
    expect(exchange.top).toEqual("Tongan Paʻanga");
    expect(exchange.try).toEqual("Turkish Lira");
    expect(exchange.ttd).toEqual("Trinidad and Tobago Dollar");
    expect(exchange.tvd).toEqual("Tuvaluan Dollar");
    expect(exchange.twd).toEqual("New Taiwan Dollar");
    expect(exchange.tzs).toEqual("Tanzanian Shilling");
    expect(exchange.uah).toEqual("Ukrainian Hryvnia");
    expect(exchange.ugx).toEqual("Ugandan Shilling");
    expect(exchange.usd).toEqual("United States Dollar");
    expect(exchange.uyu).toEqual("Uruguayan Peso");
    expect(exchange.uzs).toEqual("Uzbekistani So'm");
    expect(exchange.ves).toEqual("Venezuelan Bolívar Soberano");
    expect(exchange.vnd).toEqual("Vietnamese Đồng");
    expect(exchange.vuv).toEqual("Vanuatu Vatu");
    expect(exchange.wst).toEqual("Samoan Tālā");
    expect(exchange.xaf).toEqual("Central African CFA Franc");
    expect(exchange.xcd).toEqual("East Caribbean Dollar");
    expect(exchange.xdr).toEqual("Special Drawing Rights");
    expect(exchange.xof).toEqual("West African CFA franc");
    expect(exchange.xpf).toEqual("CFP Franc");
    expect(exchange.yer).toEqual("Yemeni Rial");
    expect(exchange.zar).toEqual("South African Rand");
    expect(exchange.zmw).toEqual("Zambian Kwacha");
  });
});